# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PTM operations CI

on:
  push:
    branches: [ operations ]
  pull_request:
    branches: [ operations ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Clean install dependencies
      working-directory: ./operations
      run: npm ci
    - name: Run test cases
      working-directory: ./operations
      run: npm test
